- hosts: localhost
  vars:
    run_only: false
    platform: "snp"
    clang_version: "16"
  tasks:
    - import_role:
        name: intel
        tasks_from: sgx-psw.yml
      when: platform == "sgx"
    - import_role:
        name: intel
        tasks_from: sgx-group.yml
      when: platform == "sgx"
    - import_role:
        name: az_dcap
        tasks_from: install.yml
      when: platform == "sgx"

    # If OE is already installed, we don't want to install hostverify as they are mutually
    # exclusive. Non-SGX CCF builds can use either of them.
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    # - name: Print package facts
    #  ansible.builtin.debug:
    #    var: ansible_facts.packages
    - import_role:
        name: openenclave
        tasks_from: install_host_verify.yml
      when: (platform != "sgx") and ("open-enclave" not in ansible_facts.packages)

    - import_role:
        name: ccf_build
        tasks_from: install.yml
    - import_role:
        name: ccf_install
        tasks_from: deb_install.yml
    - import_role:
        name: protoc
        tasks_from: install.yml
    - import_role:
        name: autoremove
        tasks_from: install.yml
